"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function CrmMfaControls() {
  const router = useRouter(); const [factor, setFactor] = useState<{ id: string; status: string } | null>(null); const [enrollment, setEnrollment] = useState<{ id: string; qr: string; secret: string } | null>(null); const [code, setCode] = useState(""); const [aal, setAal] = useState("aal1"); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function refresh() { const supabase = createClient(); const [{ data: factors }, { data: assurance }] = await Promise.all([supabase.auth.mfa.listFactors(), supabase.auth.mfa.getAuthenticatorAssuranceLevel()]); setFactor(factors?.totp.find((item) => item.status === "verified") || null); setAal(assurance?.currentLevel || "aal1"); }
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, []);
  async function enroll() { setBusy(true); const { data, error } = await createClient().auth.mfa.enroll({ factorType: "totp", friendlyName: "Anovic CRM" }); if (error) setMessage(error.message); else if (data) setEnrollment({ id: data.id, qr: data.totp.qr_code, secret: data.totp.secret }); setBusy(false); }
  async function verify(id: string) { if (!/^\d{6}$/.test(code)) { setMessage("Enter the 6-digit code."); return; } setBusy(true); const { error } = await createClient().auth.mfa.challengeAndVerify({ factorId: id, code }); setMessage(error?.message || "Authenticator verified."); if (!error) { setEnrollment(null); setCode(""); await refresh(); router.refresh(); } setBusy(false); }
  return <div className="space-y-4"><div className="flex items-center justify-between rounded-lg bg-gray-50 p-4"><div><p className="font-black">Authenticator app</p><p className="mt-1 text-xs font-bold text-gray-500">{factor ? "Enrolled" : "Not enrolled"} · {aal.toUpperCase()}</p></div><span className={`crm-badge ${factor ? "bg-indigo-50 text-indigo-700" : "bg-yellow-50 text-yellow-900"}`}>{factor ? "Protected" : "Optional"}</span></div>{!factor && !enrollment && <button className="crm-button" type="button" disabled={busy} onClick={enroll}>Set up authenticator</button>}{enrollment && <div className="rounded-lg border border-indigo-200 bg-indigo-50 p-4"><img src={enrollment.qr} alt="Authenticator QR code" className="h-48 w-48 bg-white p-2" /><p className="mt-3 break-all text-xs font-bold text-gray-600">Manual key: {enrollment.secret}</p><div className="mt-4 flex gap-2"><input className="crm-field max-w-40" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" placeholder="000000" /><button className="crm-button" type="button" disabled={busy} onClick={() => verify(enrollment.id)}>Verify</button></div></div>}{factor && aal !== "aal2" && <div className="rounded-lg border border-yellow-300 bg-yellow-50 p-4"><p className="font-black">Verify this session</p><div className="mt-3 flex gap-2"><input className="crm-field max-w-40" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" /><button className="crm-button" type="button" onClick={() => verify(factor.id)}>Verify</button></div></div>}{message && <p className="text-sm font-bold text-gray-600">{message}</p>}</div>;
}
